# Generated by Django 5.1.1 on 2024-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_name', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=40)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('gmail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, null=True)),
                ('favicon', models.FileField(blank=True, null=True, upload_to='images/settings/favicon/')),
                ('logo', models.FileField(blank=True, null=True, upload_to='images/settings/logo/')),
                ('support_1', models.URLField(blank=True, null=True)),
                ('support_2', models.URLField(blank=True, null=True)),
                ('site_year', models.CharField(max_length=20)),
                ('android_app_download_url', models.URLField(blank=True, null=True)),
                ('android_file', models.FileField(upload_to='apps/file/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='team/images/')),
                ('work_title', models.TextField()),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
