# Generated by Django 5.1.1 on 2024-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='images/user/profile/')),
                ('total_score', models.FloatField(blank=True, default=0, null=True)),
                ('month_score', models.FloatField(blank=True, default=0, null=True)),
                ('telegram_user_id', models.IntegerField(blank=True, null=True)),
                ('phone_home', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('director', 'director'), ('teacher', 'teacher'), ('student', 'student')], max_length=29)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_grand', models.BooleanField(blank=True, default=False, null=True)),
                ('is_payed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_leave', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Xabarlari',
                'verbose_name_plural': 'Foydalanuvchi Xabarlari',
                'ordering': ['-sending_date'],
            },
        ),
    ]
