# Generated by Django 5.1.1 on 2024-09-26 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('study_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='study_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_driector', to='study_center.studycenter'),
        ),
        migrations.AddField(
            model_name='account',
            name='studying',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_student', to='study_center.studycenter'),
        ),
        migrations.AddField(
            model_name='notifactionmessage',
            name='receiver',
            field=models.ManyToManyField(related_name='notifaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifactionmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
