# Generated by Django 5.1.1 on 2024-09-26 06:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kunlar',
                'verbose_name_plural': 'Kunlar',
            },
        ),
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_fanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fanlar',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('leave_student_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('group_logo', models.ImageField(blank=True, null=True, upload_to='images/group_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ManyToManyField(blank=True, to='study_center.fanlar')),
                ('students', models.ManyToManyField(blank=True, related_name='group_students', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='group_teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guruhlar',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDays',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Kunlar',
                'verbose_name_plural': 'historical Kunlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudyCenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('logo', models.TextField(max_length=100)),
                ('admin', models.IntegerField(choices=[(1, 'Admin 1'), (2, 'Admin 2'), (3, 'Admin 3')])),
                ('address', models.CharField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical O'quv markazlar",
                'verbose_name_plural': "historical O'quv markazlar",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LessonsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_center.group')),
            ],
            options={
                'verbose_name': 'Dars jadvallar',
                'verbose_name_plural': 'Dars jadvallar',
            },
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba'), ('Yakshanba', 'Yakshanba')], max_length=10)),
                ('time', models.TimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='study_center.lessonstable')),
            ],
            options={
                'verbose_name': 'Dars vaqtlari',
                'verbose_name_plural': 'Dars vaqtlari',
            },
        ),
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='images/StudyCenters/')),
                ('admin', models.IntegerField(choices=[(1, 'Admin 1'), (2, 'Admin 2'), (3, 'Admin 3')])),
                ('address', models.CharField(max_length=500)),
                ('students', models.ManyToManyField(blank=True, related_name='learning_centers', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quv markazlar",
                'verbose_name_plural': "O'quv markazlar",
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('MAHSULOTGA', 'MAHSULOTGA'), ("OYLIK TO'LOV UCHUN", "OYLIK TO'LOV UCHUN")], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_center.fanlar')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to=settings.AUTH_USER_MODEL)),
                ('study_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_center.studycenter')),
            ],
            options={
                'verbose_name': "To'lovlar",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='lessonstable',
            name='study_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_center.studycenter'),
        ),
        migrations.CreateModel(
            name='HistoricalPayments',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('MAHSULOTGA', 'MAHSULOTGA'), ("OYLIK TO'LOV UCHUN", "OYLIK TO'LOV UCHUN")], max_length=50)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_center.fanlar')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_center.studycenter')),
            ],
            options={
                'verbose_name': "historical To'lovlar",
                'verbose_name_plural': "historical To'lovlar",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('leave_student_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('group_logo', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('update_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_center.studycenter')),
            ],
            options={
                'verbose_name': 'historical Guruhlar',
                'verbose_name_plural': 'historical Guruhlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFanlar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_center.studycenter')),
            ],
            options={
                'verbose_name': 'historical Fanlar',
                'verbose_name_plural': 'historical Fanlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='group',
            name='study_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='study_center.studycenter'),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='study_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_center', to='study_center.studycenter'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_center.group')),
                ('study_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_center.studycenter')),
            ],
            options={
                'verbose_name': 'Davomatlar Record',
                'verbose_name_plural': 'Davomat Record',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_center.lessonschedule')),
                ('study_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_center.studycenter')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
            },
        ),
    ]
